# Generated by Django 5.1.4 on 2025-01-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_track', '0002_alter_category_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tag',
            field=models.CharField(default='support', max_length=50),
            preserve_default=False,
        ),
    ]
