# Generated by Django 5.1.4 on 2025-01-05 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory_track', '0005_alter_ldapuser_company_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.AddField(
            model_name='category',
            name='created_by_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
