# Generated by Django 5.1.4 on 2025-01-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_track', '0006_remove_category_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='Brand',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='model',
            table='Model',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='productstatus',
            table='ProductStatus',
        ),
    ]
